server:
  error:
    include-stacktrace: always
    include-message: always
spring:
  datasource:
    url: jdbc:h2:file:./database
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
  sql:
    init:
      mode: always